# Generated by Django 5.0.3 on 2024-03-22 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idZE', models.CharField(max_length=20, unique=True, verbose_name='Identificador da Zona Eleitoral')),
                ('qtdEleitoresAptos', models.IntegerField(verbose_name='Quantidade de Eleitores Aptos')),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('muni_id', models.AutoField(primary_key=True, serialize=False)),
                ('KM_Cuiaba', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sede', models.BooleanField(default=False)),
                ('qtd_secao', models.IntegerField()),
                ('mrjs', models.IntegerField()),
                ('qtd_ue', models.IntegerField()),
                ('qtd_ue_cont', models.IntegerField()),
                ('zona_eleitoral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='logis.ze')),
            ],
        ),
    ]
