# Generated by Django 5.0.3 on 2024-04-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logis', '0002_tsat_ue_alter_municipios_options_alter_ze_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipios',
            name='nome',
            field=models.CharField(default='sem_nome', max_length=100),
        ),
    ]
