# Generated by Django 5.0.6 on 2024-06-03 13:52

import django.db.models.deletion
import logisApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEleitoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('UE', 'Urna Eletrônica'), ('Cabine', 'Cabine de Votação'), ('Bateria', 'Bateria'), ('MidiaResultado', 'Mídia de Resultado'), ('MidiaAplicacao', 'Mídia de Aplicação'), ('CaboFast', 'Cabo Fast'), ('CaboJacare', 'Cabo Jacaré'), ('CaboUSB', 'Cabo USB'), ('LeitorFlash', 'Leitor de Flash'), ('Reposicao', 'Componente de Reposição')], max_length=20)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Urna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default='2024', max_length=4, validators=[logisApp.models.validate_year])),
                ('bio', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaEleitoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_manutencao', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('tecnico_responsavel', models.CharField(max_length=200)),
                ('urna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logisApp.urna')),
            ],
        ),
        migrations.CreateModel(
            name='ZE_solicita_urna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.IntegerField()),
                ('urna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logisApp.urna')),
                ('zona_eleitoral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logisApp.zonaeleitoral')),
            ],
        ),
        migrations.AddField(
            model_name='urna',
            name='zona_eleitoral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logisApp.zonaeleitoral'),
        ),
        migrations.CreateModel(
            name='SolicitaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logisApp.materialeleitoral')),
                ('zona_eleitoral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logisApp.zonaeleitoral')),
            ],
        ),
        migrations.CreateModel(
            name='MunicipioZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logisApp.municipio')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logisApp.zonaeleitoral')),
            ],
        ),
    ]
