# Generated by Django 5.0.6 on 2024-06-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urna',
            name='modelo',
            field=models.CharField(choices=[('2008', '2008'), ('2010', '2010'), ('2012', '2012'), ('2015', '2015'), ('2018', '2018'), ('2020', '2020'), ('2023', '2023')], max_length=4),
        ),
    ]
