# Generated by Django 5.0.6 on 2024-06-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisApp', '0002_alter_urna_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonaeleitoral',
            name='qtdSecoes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zonaeleitoral',
            name='qtdUrnasEstoque',
            field=models.IntegerField(default=0),
        ),
    ]
