# Generated by Django 5.0.6 on 2024-07-16 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisApp', '0002_municipio_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_municipio', models.CharField(max_length=8)),
                ('cod_local', models.CharField(max_length=10)),
                ('cod_secao', models.CharField(max_length=10)),
                ('ind_especial', models.CharField(max_length=1)),
                ('cod_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logisApp.zonaeleitoral')),
            ],
        ),
    ]
