# Generated by Django 5.0.6 on 2024-07-19 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisApp', '0004_distributionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionlog',
            name='distributed_by',
        ),
        migrations.RemoveField(
            model_name='distributionlog',
            name='material_eleitoral',
        ),
        migrations.RemoveField(
            model_name='distributionlog',
            name='zona_eleitoral',
        ),
        migrations.RemoveField(
            model_name='distributionlog',
            name='zona_eleitoral_name',
        ),
        migrations.AlterField(
            model_name='distributionlog',
            name='distribution_type',
            field=models.CharField(choices=[('MRV', 'Primário'), ('CONT', 'Contingência')], max_length=50),
        ),
        migrations.CreateModel(
            name='Distribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('distributed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='distributionlog',
            name='distribuicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='logisApp.distribuicao'),
            preserve_default=False,
        ),
    ]
