# Generated by Django 5.0.6 on 2024-06-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisApp', '0005_urna_qtd'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonaeleitoral',
            name='qtdUrnasCont',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zonaeleitoral',
            name='qtdUrnasMRV',
            field=models.IntegerField(default=0),
        ),
    ]
