# Generated by Django 5.0.6 on 2024-07-31 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisApp', '0006_distributionlog_distributed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.IntegerField()),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicao', to='logisApp.distribuicao')),
                ('urna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logisApp.urna')),
                ('zona_eleitoral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logisApp.zonaeleitoral')),
            ],
        ),
        migrations.DeleteModel(
            name='ZE_solicita_urna',
        ),
    ]
