# Generated by Django 5.0.6 on 2024-08-05 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisApp', '0008_alter_solicitacao_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuicao',
            name='stock_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logisApp.zonaeleitoral'),
        ),
        migrations.AlterField(
            model_name='zonaeleitoral',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zonaeleitoral',
            name='qtdSecoes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zonaeleitoral',
            name='qtdUrnasCont',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zonaeleitoral',
            name='qtdUrnasEstoque',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zonaeleitoral',
            name='qtdUrnasMRV',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
